config/routes.rb
TaskMNGR::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  root 'users#index'
  resources :projects, only: [:index, :show, :create, :destroy]
  resources :tasks, only: [:create, :destroy] do
    member do
      post :change_up_priority, :change_down_priority
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base

	has_many :tasks, dependent: :destroy

	validates :name, presence: { message: 'Please provide a name' }

	def logged
		logs.map(&:duration).sum
	end
end

app/models/task.rb
class Task < ActiveRecord::Base

	belongs_to :project

	default_scope { order(:priority) }

	validates :name, presence: { message: 'Please provide a name' }
	validates_presence_of :project

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :projects
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, length: { minimum: 6 }

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

	def create_remember_token
		self.remember_token = User.encrypt(User.new_remember_token)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index
		@projects = Projects.all
		@project = Project.first
	end

	def show
		@project = Project.find(params[:id])
	end

	def create
		@project = Project.create(name: params[:name], user_id: current_user.id)
    	@projects = Project.all
  	end

  	def destroy
   	 	@deleted = Project.find(params[:id]).destroy
   	 	@project = Project.first
    	render :show
 	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(email: params[:email].downcase)
		if user && user.authenticate(params[:password])
			sign_in user
			redirect_to user
		else
			flash.now[:error] = 'Invalid email/password combination'	
		end
	end

	def destroy
		sign_out
	end
	
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def create
    if params[:name].length>27
      abort("too long")
    end
    if !Project.find(params[:project_id]).tasks.first
      @task = Project.find(params[:project_id]).tasks.create(name: params[:name], priority: 1)
    else
      new_priority = Project.find(params[:project_id]).tasks.maximum(:priority) + 1
      @task = Project.find(params[:project_id]).tasks.create(name: params[:name], priority: new_priority)
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
  end

  def change_up_priority
    @task_current = Task.find_by(id: params[:id])
    if @task_current.priority != 1
      @task_next = Task.find_by(priority: @task_current.priority.to_i + params[:priority].to_i, project_id: @task_current.project_id)
      @task_current.decrement!(:priority)
      @task_next.increment!(:priority)
      @task_current.save
      @task_next.save
    end
  end

  def change_down_priority
    @task_current = Task.find_by(id: params[:id])
    project_current = Project.find_by(id: @task_current.project_id)
    @max = project_current.tasks.maximum("priority")
    if @task_current.priority != @max
      @task_next = Task.find_by(priority: @task_current.priority.to_i + params[:priority].to_i, project_id: @task_current.project_id)
      @task_current.increment!(:priority)
      @task_next.decrement!(:priority)
      @task_current.save
      @task_next.save
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  	render :sign_up
  end

  def create
  	@user = User.new(user_params)
    @projects = Project.all
  	if @user.save
  		sign_in @user
  		flash[:success] = "Welcome!"
      render :show
  	end
  end
  
  def show
  	@user = User.find(params[:id])
  	@projects = Project.all
    @project = Project.first
  end

  def index
    if signed_in?
      @user = User.find(current_user.id)
      @projects = Project.all
      @project = Project.first
    end
  end

  def user_params
	params.permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
    	remember_token = User.new_remember_token
    	cookies.permanent[:remember_token] = remember_token
    	user.update_attribute(:remember_token, User.encrypt(remember_token))
    	self.current_user = user
  	end

  	def signed_in?
  		!current_user.nil?
  	end

  	def current_user=(user)
  		@current_user = user
  	end

  	def current_user
    	remember_token = User.encrypt(cookies[:remember_token])
    	@current_user ||= User.find_by(remember_token: remember_token)
  	end

    def sign_out
      current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
      cookies.delete(:remember_token)
      self.current_user = nil
    end

end

app/helpers/users_helper.rb
module UsersHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app>
<head>
  <title>TaskMNGR</title>
  <%= stylesheet_link_tag    "application", media: "all"%>
  <%= javascript_include_tag "application", controller_name %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_project.html.haml
%div{class: "project project-#{project.id}"}
  .panel.panel-primary
    .panel-heading
      .row.project-heading
        .pull-left
          %span{ class:"glyphicon glyphicon-tasks"}
        .col-xs-8
          =project.name
        .pull-right
          = link_to project_path(:id => project.id), remote: true, method: :delete, class: "btn btn-default btn-xs", style:"background: transparent; border: none; padding: 0;" do
            %span.glyphicon.glyphicon-trash
    .panel-body
      .input-group
        %span{ class:"input-group-addon"}
          %span{ class:"glyphicon glyphicon-plus"}
        = form_tag('/tasks', method: :post, remote: true, class:"form-inline") do
          .row
          .col-xs-8.nopadding
            = text_field_tag(:name, nil, placeholder: 'New task', class:"form-control add-task-form", type:"text",style:"width: 100%;")
            = hidden_field_tag(:project_id, "#{@projects.empty? ? 0 : project.id}")
          .col-xs-4.nopadding
            = submit_tag 'Add task', class:"btn btn-default add-task-button", style:"float: right; width: 100%;"
      
      .taskpane
        = render project.tasks


 
  
  

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/tasks/_task.html.haml
%div{class: "task project-#{task.project_id} priority-#{task.priority}" , id: "playfield"}
  .row.task-row
    .col-md-1.col-xs-2
      .task-check-box
        %input{type:"checkbox"}
    .col-md-7.col-xs-6
      .task-name
        = task.name
    .col-md-4.col-xs-4.priority
      .task-control
        = link_to change_down_priority_task_path(:id => task.id, :priority => "1", :project_id => task.project_id), remote: true, method: :post, :onclick => "return changePriorityDown(#{task.priority}, #{task.project_id});", class: "btn btn-default btn-xs down", style:"background: transparent; border: none; padding: 0;" do
          %span.glyphicon.glyphicon-arrow-down
        = link_to change_up_priority_task_path(:id => task.id, :priority => "-1"), remote: true, method: :post, :onclick => "return changePriorityUp(#{task.priority}, #{task.project_id});", class: "btn btn-default btn-xs up", style:"background: transparent; border: none; padding: 0;" do
          %span.glyphicon.glyphicon-arrow-up

app/views/users/_show.html.haml
.projects
  = link_to 'sign out', session_path(:id => @user.id), remote: true, method: :delete, class:"button btn btn-default", type:"button"
  .row
    .col-md-6.col-md-offset-3.col-xs-10.col-xs-offset-1.project-create
      - if @projects.size > 0
        - @user.projects.each do |project|
          = render project
  .row
    .col-md-2.col-md-offset-5.col-xs-4.col-xs-offset-4
      %button.btn.btn-default{type: "button", :onclick => "return ProjectNameInput();"} Add TODO list

app/views/users/_sign_up.html.haml
.sign-up
  .col-md-6.col-md-offset-3.col-xs-10.col-xs-offset-1.sign-form
    = form_tag(@user,:class => "form-horizontal", :name => "sign-up_form", :onsubmit => "return validateSignUpForm();", method: :post, remote: true) do
      %fieldset
        %legend Sign Up
        .form-group
          %label.col-lg-2.control-label{for: "inputName"} Name
          .col-lg-10
            = text_field_tag( :name, nil,:class => "form-control", :id => "inputName", placeholder: 'name' )
        .form-group
          %label.col-lg-2.control-label{for: "inputEmail"} Email
          .col-lg-10
            = text_field_tag( :email, nil,:class => "form-control", :id => "inputEmail", placeholder: 'email' )
        .form-group 
          %label.col-lg-2.control-label{for: "inputPassword"} Password
          .col-lg-10
            = password_field_tag( :password, nil, :class => "form-control", :id => "inputPassword", placeholder: 'password' ) 
        .form-group 
          %label.col-lg-2.control-label{for: "inputPasswordConfirmation"} Password Confirmation
          .col-lg-10
            = password_field_tag( :password_confirmation, nil, :class => "form-control", :id => "inputPasswordConfirmation", placeholder: 'password confirmation' ) 
        .form-group
          .col-lg-10.col-lg-offset-2
            = submit_tag  'sign up', class: "btn btn-primary"
            = link_to 'sign in', new_session_path, { :class => "btn btn-primary", remote: true, method: :get }

app/views/users/index.html.haml
- if !signed_in?
  =render :partial => "sessions/sign_in", :type => "haml"
- else
  =render :partial => "users/show", :type => "haml"